/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Main {


    public static void main(String[] args) {
        System.out.println("main");
    }

    public String greet(String name) {
        return "Hi! %s".formatted(name);
    }
}
