/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Optional;

public class Main {
    public String getGreeting(String name) {
        return Optional.ofNullable(name)
                .map((s) -> "Hello World! " + s)
                .orElse("Hello World!");
    }

    public static void main(String[] args) {
        System.out.println(new Main().getGreeting("name"));
    }
}
