/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class MainTest {

    private Main greater;

    @BeforeEach
    void setUp() {
        greater = new Main();
    }

    @Test
    @DisplayName("should greet with name")
    void shouldGreetWithName() {
        //given
        var fullName = "Full Name";
        //when
        var greet = greater.getGreeting(fullName);
        //then
        assertThat(greet).isEqualTo("Hello World! Full Name");
    }
}
