/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class MainTest {

    private Main greater;

    @BeforeEach
    void setUp() {
        greater = new Main();
    }

    @Test
    @DisplayName("should greet when no name")
    void shouldGreetWhenNoName() {
        //when
        var greeting = greater.getGreeting(null);
        //then
        assertThat(greeting).isEqualTo("Hello World!");
    }

    @Test
    @DisplayName("should greet with name")
    void shouldGreetWithName() {
        //given
        var fullName = "full name";
        //when
        var greeting = greater.getGreeting(fullName);
        //thenR
        assertThat(greeting).isEqualTo("Hello World! full name");
    }
}
