/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.fail;

class MainTest {
    @Test
    @DisplayName("should greet when name is not empty")
    void shouldGreetWhenNameIsNotEmpty() {
        //given

        //when

        //then
        fail("Not implemented");
    }
}
